version: '3'

services:

#
# nzbget
# NZBGet is a usenet downloader, written in C++ and designed with performance in mind to achieve maximum download speed by using very little system resources.
#
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    restart: always
    volumes:
      - /run
      - $HOME/nzbget:/config
      - $HOME/Downloads:/downloads
      - $HOME/Downloads/incomplete:/incomplete-downloads
    environment:
      - PGID=1000
      - PUID=1000
      - TZ=Europe/Brussels
    ports:
      - 6789:6789
    networks:
      - app_net
    healthcheck:
     test: ["CMD-SHELL", "curl -f http://localhost:6789 && echo 'OK'"]
     interval: 5s
     timeout: 2s
     retries: 20

#
# watchtower
# Watchtower is an application that will monitor your running Docker containers and watch for changes to the images that those containers were originally started from.
# If watchtower detects that an image has changed, it will automatically restart the container using the new image.
#
  watchtower:
    image: v2tec/watchtower
    container_name: watchtower
    privileged: true
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup

networks:
  app_net:
    driver: bridge
    ipam:
     driver: default
     config:
      - subnet: 172.19.0.0/16

